"""add phone number

Revision ID: 11abbf74ba3e
Revises: 393166abe7ba
Create Date: 2022-01-28 13:46:47.423065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11abbf74ba3e'
down_revision = '393166abe7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
